export const BLOCK_PARTICLE_SYSTEM = {
  enabled: true,
  autoPlay: false, // CUSTOM
  numParticles: 15,
  lifetime: 0.8,
  rate: 0,
  rate2: 0,
  startAngle: 0,
  startAngle2: 0,
  preWarm: false,
  lighting: false,
  halfLambert: false,
  intensity: 1,
  depthWrite: false,
  depthSoftening: 0,
  sort: 0,
  blendType: 2,
  stretch: 0,
  loop: false,
  alignToMotion: false,
  emitterShape: 1,
  emitterExtents: [0, 0, 0],
  emitterExtentsInner: [0, 0, 0],
  orientation: 0,
  particleNormal: [0, 1, 0],
  emitterRadius: 0,
  emitterRadiusInner: 0,
  initialVelocity: 0,
  animTilesX: 1,
  animTilesY: 1,
  animStartFrame: 0,
  animNumFrames: 1,
  animNumAnimations: 1,
  animIndex: 0,
  randomizeAnimIndex: false,
  animSpeed: 2,
  animLoop: false,
  wrap: false,
  wrapBounds: [0, 0, 0],
  colorMapAsset: null, // CUSTOM
  normalMapAsset: null,
  mesh: null,
  renderAsset: null,
  localSpace: false,
  screenSpace: false,
  localVelocityGraph: {
    type: 1,
    keys: [
      [0, 0],
      [0, 0],
      [0, 0],
    ],
    betweenCurves: false,
  },
  localVelocityGraph2: {
    type: 1,
    keys: [
      [0, 0],
      [0, 0],
      [0, 0],
    ],
  },
  velocityGraph: {
    type: 1,
    keys: [
      [0, -2],
      [0, -2],
      [0, 0],
    ],
    betweenCurves: true,
  },
  velocityGraph2: {
    type: 1,
    keys: [
      [0, 1],
      [0, 1],
      [0, 0],
    ],
  },
  rotationSpeedGraph: {
    type: 1,
    keys: [0, 0],
    betweenCurves: false,
  },
  rotationSpeedGraph2: {
    type: 1,
    keys: [0, 0],
  },
  radialSpeedGraph: {
    type: 1,
    keys: [0, 0],
    betweenCurves: false,
  },
  radialSpeedGraph2: {
    type: 1,
    keys: [0, 0],
  },
  scaleGraph: {
    type: 1,
    keys: [0, 0.5],
    betweenCurves: false,
  },
  scaleGraph2: {
    type: 1,
    keys: [0, 0.2],
  },
  colorGraph: {
    type: 4,
    keys: [
      [0, 1],
      [0, 1],
      [0, 1],
    ],
    betweenCurves: false,
  },
  alphaGraph: {
    type: 1,
    keys: [0, 1, 1, 0],
    betweenCurves: false,
  },
  alphaGraph2: {
    type: 1,
    keys: [0, 1, 1, 0],
  },
  layers: [0],
};

export const SOUNDS = {
  enabled: true,
  volume: 1,
  pitch: 1,
  positional: false,
  slots: {
    2: {
      name: "bgm",
      loop: true,
      autoPlay: false,
      overlap: false,
      asset: 100,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    3: {
      name: "bubble",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 101,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    4: {
      name: "button",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 102,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    5: {
      name: "cartoon pop",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 103,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    6: {
      name: "close",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 104,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    7: {
      name: "coin pop",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 105,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    8: {
      name: "harp",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 106,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    9: {
      name: "level up",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 107,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    10: {
      name: "life pop",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 108,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    11: {
      name: "lose",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 109,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    12: {
      name: "magical",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 110,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    13: {
      name: "pause enter",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 111,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    14: {
      name: "pop close",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 112,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    15: {
      name: "pop",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 113,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    16: {
      name: "spin wheel prize",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 114,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    17: {
      name: "spin wheel",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 115,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
    18: {
      name: "win",
      loop: false,
      autoPlay: false,
      overlap: true,
      asset: 116,
      startTime: 0,
      duration: null,
      volume: 1,
      pitch: 1,
    },
  },
};
