export const BLOCK_PARTICLE_SYSTEM = {
  enabled: true,
  autoPlay: false, // CUSTOM
  numParticles: 15,
  lifetime: 0.8,
  rate: 0,
  rate2: 0,
  startAngle: 0,
  startAngle2: 0,
  preWarm: false,
  lighting: false,
  halfLambert: false,
  intensity: 1,
  depthWrite: false,
  depthSoftening: 0,
  sort: 0,
  blendType: 2,
  stretch: 0,
  loop: false,
  alignToMotion: false,
  emitterShape: 1,
  emitterExtents: [0, 0, 0],
  emitterExtentsInner: [0, 0, 0],
  orientation: 0,
  particleNormal: [0, 1, 0],
  emitterRadius: 0,
  emitterRadiusInner: 0,
  initialVelocity: 0,
  animTilesX: 1,
  animTilesY: 1,
  animStartFrame: 0,
  animNumFrames: 1,
  animNumAnimations: 1,
  animIndex: 0,
  randomizeAnimIndex: false,
  animSpeed: 2,
  animLoop: false,
  wrap: false,
  wrapBounds: [0, 0, 0],
  colorMapAsset: null, // CUSTOM
  normalMapAsset: null,
  mesh: null,
  renderAsset: null,
  localSpace: false,
  screenSpace: false,
  localVelocityGraph: {
    type: 1,
    keys: [
      [0, 0],
      [0, 0],
      [0, 0],
    ],
    betweenCurves: false,
  },
  localVelocityGraph2: {
    type: 1,
    keys: [
      [0, 0],
      [0, 0],
      [0, 0],
    ],
  },
  velocityGraph: {
    type: 1,
    keys: [
      [0, -2],
      [0, -2],
      [0, 0],
    ],
    betweenCurves: true,
  },
  velocityGraph2: {
    type: 1,
    keys: [
      [0, 1],
      [0, 1],
      [0, 0],
    ],
  },
  rotationSpeedGraph: {
    type: 1,
    keys: [0, 0],
    betweenCurves: false,
  },
  rotationSpeedGraph2: {
    type: 1,
    keys: [0, 0],
  },
  radialSpeedGraph: {
    type: 1,
    keys: [0, 0],
    betweenCurves: false,
  },
  radialSpeedGraph2: {
    type: 1,
    keys: [0, 0],
  },
  scaleGraph: {
    type: 1,
    keys: [0, 0.5],
    betweenCurves: false,
  },
  scaleGraph2: {
    type: 1,
    keys: [0, 0.2],
  },
  colorGraph: {
    type: 4,
    keys: [
      [0, 1],
      [0, 1],
      [0, 1],
    ],
    betweenCurves: false,
  },
  alphaGraph: {
    type: 1,
    keys: [0, 1, 1, 0],
    betweenCurves: false,
  },
  alphaGraph2: {
    type: 1,
    keys: [0, 1, 1, 0],
  },
  layers: [0],
};
