export const THEME = {
  valentine: {
    palette: {
      /* 초콜릿 색상 스케일 */
      "--color-main-100": "#fdf0e6" /* 가장 연한 크림색 */,
      "--color-main-200": "#f5e1d0" /* 매우 연한 베이지 */,
      "--color-main-300": "#e6cdb7" /* 연한 베이지 */,
      "--color-main-400": "#d4b69b" /* 밝은 카라멜 */,
      "--color-main-500": "#c4a484" /* 중간 톤의 초콜릿 */,
      "--color-main-600": "#b08e6b" /* 카라멜 밀크 */,
      "--color-main-700": "#9b7960" /* 진한 카라멜 */,
      "--color-main-800": "#866555" /* 다크 초콜릿 */,
      "--color-main-900": "#6f4e45" /* 가장 진한 초콜릿 */,
    },
    textures: [
      "/assets/valentine/level_0.png",
      "/assets/valentine/level_1.png",
      "/assets/valentine/level_2.png",
      "/assets/valentine/level_3.png",
      "/assets/valentine/level_4.png",
      "/assets/valentine/level_5.png",
      "/assets/valentine/level_6.png",
      "/assets/valentine/level_7.png",
      "/assets/valentine/level_8.png",
      "/assets/valentine/level_9.png",
      "/assets/valentine/level_10.png",
    ],
  },
  dark: {
    palette: {
      "--color-main-100": "#2e2e2e",
      "--color-main-200": "#3c3c3c",
      "--color-main-300": "#4a4a4a",
      "--color-main-400": "#585858",
      "--color-main-500": "#666666",
      "--color-main-600": "#747474",
      "--color-main-700": "#828282",
      "--color-main-800": "#909090",
      "--color-main-900": "#9e9e9e",
      "--color-surface": "#1a1a1a",
      "--color-background": "#2e2e2e",
      "--color-overlay": "rgba(255, 255, 255, 0.5)",
    },
    textures: [
      "/assets/dark/level_0.png",
      "/assets/dark/level_1.png",
      "/assets/dark/level_2.png",
      "/assets/dark/level_3.png",
      "/assets/dark/level_4.png",
      "/assets/dark/level_5.png",
      "/assets/dark/level_6.png",
      "/assets/dark/level_7.png",
      "/assets/dark/level_8.png",
      "/assets/dark/level_9.png",
      "/assets/dark/level_10.png",
    ],
  },
};
