export const THEME = {
  valentine: {
    palette: {
      /* 초콜릿 색상 스케일 */
      "--color-main-100": "#fdf0e6" /* 가장 연한 크림색 */,
      "--color-main-200": "#f5e1d0" /* 매우 연한 베이지 */,
      "--color-main-300": "#e6cdb7" /* 연한 베이지 */,
      "--color-main-400": "#d4b69b" /* 밝은 카라멜 */,
      "--color-main-500": "#c4a484" /* 중간 톤의 초콜릿 */,
      "--color-main-600": "#b08e6b" /* 카라멜 밀크 */,
      "--color-main-700": "#9b7960" /* 진한 카라멜 */,
      "--color-main-800": "#866555" /* 다크 초콜릿 */,
      "--color-main-900": "#6f4e45" /* 가장 진한 초콜릿 */,
    },
    textures: [
      "/assets/valentine/block_0.png",
      "/assets/valentine/block_1.png",
      "/assets/valentine/block_2.png",
      "/assets/valentine/block_3.png",
      "/assets/valentine/block_4.png",
      "/assets/valentine/block_5.png",
      "/assets/valentine/block_6.png",
      "/assets/valentine/block_7.png",
      "/assets/valentine/block_8.png",
      "/assets/valentine/block_9.png",
      "/assets/valentine/block_10.png",
    ],
  },
  default: {
    palette: {
      "--color-main-100": "#ffffff" /* 가장 연한 흰색 */,
      "--color-main-200": "#f0f0f0" /* 매우 연한 회색 */,
      "--color-main-300": "#d9d9d9" /* 연한 회색 */,
      "--color-main-400": "#bfbfbf" /* 중간 톤의 회색 */,
      "--color-main-500": "#a6a6a6" /* 진한 회색 */,
      "--color-main-600": "#8c8c8c" /* 더 진한 회색 */,
      "--color-main-700": "#737373" /* 어두운 회색 */,
      "--color-main-800": "#595959" /* 매우 어두운 회색 */,
      "--color-main-900": "#404040" /* 가장 어두운 회색 */,
      "--color-surface": "#1a1a1a" /* 거의 검정 */,
      "--color-background": "#0a0a0a" /* 검정 */,
      "--color-overlay": "rgba(255, 255, 255, 0.1)" /* 은하수 효과 */,
    },
    textures: [
      "/assets/default/block_0.png",
      "/assets/default/block_1.png",
      "/assets/default/block_2.png",
      "/assets/default/block_3.png",
      "/assets/default/block_4.png",
      "/assets/default/block_5.png",
      "/assets/default/block_6.png",
      "/assets/default/block_7.png",
      "/assets/default/block_8.png",
      "/assets/default/block_9.png",
      "/assets/default/block_10.png",
    ],
  },
  candy: {
    palette: {
      /* 파스텔 분홍색과 보라색 스케일 */
      "--color-main-100": "#f9f5fb" /* 가장 연한 라벤더 */,
      "--color-main-200": "#f3e8f7" /* 매우 연한 라벤더 */,
      "--color-main-300": "#ecdaf3" /* 연한 라벤더 */,
      "--color-main-400": "#e3c9ee" /* 밝은 라벤더 */,
      "--color-main-500": "#dab8e9" /* 중간 톤의 라벤더 */,
      "--color-main-600": "#d1a7e4" /* 진한 라벤더 */,
      "--color-main-700": "#c393db" /* 더 진한 라벤더 */,
      "--color-main-800": "#b57fd2" /* 매우 진한 라벤더 */,
      "--color-main-900": "#a66bc9" /* 가장 진한 라벤더 */,
      "--color-surface": "#f5f0f9" /* 연한 배경색 */,
      "--color-background": "#faf5fc" /* 흰색에 가까운 배경 */,
      "--color-overlay": "rgba(192, 192, 255, 0.1)" /* 보라빛 오버레이 */,
    },
    textures: [
      "/assets/candy/block_0.png",
      "/assets/candy/block_1.png",
      "/assets/candy/block_2.png",
      "/assets/candy/block_3.png",
      "/assets/candy/block_4.png",
      "/assets/candy/block_5.png",
      "/assets/candy/block_6.png",
      "/assets/candy/block_7.png",
      "/assets/candy/block_8.png",
      "/assets/candy/block_9.png",
      "/assets/candy/block_10.png",
    ],
  },
};
